databases:
  dev:
    username: sa
    password: euPK#sp8[dL!(4M/m+*AYk]~fvZ;rN>g
    host: app-mssql_server-1
    port: 1433
    database: future_interns
    connectionTimeout: 5
    encrypt: false
  testing:
    username: sa
    password: mssql-server-2-pass
    host: 192.168.144.152
    port: 1433
    database: future_interns
    connectionTimeout: 5
    encrypt: false
  prod:
    username: prod
    password: prod
    host: prod
    port: 1433
    instance: prod
    database: prod
    connectionTimeout: 5
    encrypt: false

authorization:
  jwt:
    secretKey: "sidokaredev24"
