mssql:
  dev:
    username: adm_futureinterns
    password: passfutureinterns
    host: localhost
    port: 1433
    instance: sidokaredev
    database: future_interns
    connectionTimeout: 5
    encrypt: false

redis:
  dev:
    address: localhost:6379
    password: ""
    database: 0
    protocol: 3
    
authorization:
  jwt:
    secretKey: sidokaredev24