status: config activated

databases:
  dev:
    username: sa
    password: euPK#sp8[dL!(4M/m+*AYk]~fvZ;rN>g
    host: app-mssql_server-1
    port: 1433
    database: future_interns
    connectionTimeout: 5
    encrypt: false
  testing:
    username: sa
    password: euPK#sp8[dL!(4M/m+*AYk]~fvZ;rN>g
    host: skripsi-mssql_server-1
    port: 1433
    database: future_interns
    connectionTimeout: 5
    encrypt: false
