package constants

var LineIndustries = []string{
	"IT and Technology",
	"Finance",
	"Construction and Real Estate",
	"Insurance",
	"Retail and E-commerce",
	"Entertainment and Media",
	"Transportation and Logistics",
	"Telecommunications",
	"Education",
	"Legal Services",
}

var EmployeeType = []string{
	"Full-time",
	"Part-time",
	"Contract",
	"Freelance",
	"Internship",
	"Temporary",
	"Volunteer",
	"Remote",
	"On-call",
	"Seasonal",
}

var WorkArrangements = []string{
	"On-site",
	"Remote",
	"Hybrid",
	"Flexible Hours",
	"Shift-based",
	"Compressed Workweek",
	"Freelance/Project-based",
	"Rotational",
}

var Provinces = []string{
	"Aceh",
	"Sumatera Utara",
	"Sumatera Barat",
	"Riau",
	"Jambi",
	"Sumatera Selatan",
	"Bengkulu",
	"Lampung",
	"Kepulauan Bangka Belitung",
	"Kepulauan Riau",
	"DKI Jakarta",
	"Jawa Barat",
	"Jawa Tengah",
	"DI Yogyakarta",
	"Jawa Timur",
	"Banten",
	"Bali",
	"Nusa Tenggara Barat",
	"Nusa Tenggara Timur",
	"Kalimantan Barat",
	"Kalimantan Tengah",
	"Kalimantan Selatan",
	"Kalimantan Timur",
	"Kalimantan Utara",
	"Sulawesi Utara",
	"Sulawesi Tengah",
	"Sulawesi Selatan",
	"Sulawesi Tenggara",
	"Gorontalo",
	"Sulawesi Barat",
	"Maluku",
	"Maluku Utara",
	"Papua",
	"Papua Barat",
}
